# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 120, 1000, 750))
        self.widget.setObjectName("widget")
        self.SetUp = QtWidgets.QPushButton(self.centralwidget)
        self.SetUp.setGeometry(QtCore.QRect(610, 30, 131, 71))
        self.SetUp.setObjectName("SetUp")
        self.Goal = QtWidgets.QPushButton(self.centralwidget)
        self.Goal.setGeometry(QtCore.QRect(880, 30, 131, 71))
        self.Goal.setObjectName("Goal")
        self.Up = QtWidgets.QPushButton(self.centralwidget)
        self.Up.setGeometry(QtCore.QRect(60, 150, 91, 91))
        self.Up.setObjectName("Up")
        self.Down = QtWidgets.QPushButton(self.centralwidget)
        self.Down.setGeometry(QtCore.QRect(60, 260, 91, 91))
        self.Down.setObjectName("Down")
        self.Right = QtWidgets.QPushButton(self.centralwidget)
        self.Right.setGeometry(QtCore.QRect(180, 260, 91, 91))
        self.Right.setObjectName("Right")
        self.Left = QtWidgets.QPushButton(self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(180, 150, 91, 91))
        self.Left.setObjectName("Left")
        self.Clock = QtWidgets.QPushButton(self.centralwidget)
        self.Clock.setGeometry(QtCore.QRect(60, 370, 91, 91))
        self.Clock.setObjectName("Clock")
        self.ReClock = QtWidgets.QPushButton(self.centralwidget)
        self.ReClock.setGeometry(QtCore.QRect(180, 370, 91, 91))
        self.ReClock.setObjectName("ReClock")
        self.Select = QtWidgets.QPushButton(self.centralwidget)
        self.Select.setGeometry(QtCore.QRect(60, 40, 111, 41))
        self.Select.setObjectName("Select")
        self.Load_dxf = QtWidgets.QPushButton(self.centralwidget)
        self.Load_dxf.setGeometry(QtCore.QRect(200, 40, 111, 41))
        self.Load_dxf.setObjectName("Load_dxf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SetUp.setText(_translate("MainWindow", "SetUp"))
        self.Goal.setText(_translate("MainWindow", "Goal"))
        self.Up.setText(_translate("MainWindow", "Up"))
        self.Down.setText(_translate("MainWindow", "Down"))
        self.Right.setText(_translate("MainWindow", "Right"))
        self.Left.setText(_translate("MainWindow", "Left"))
        self.Clock.setText(_translate("MainWindow", "Clock"))
        self.ReClock.setText(_translate("MainWindow", "CounterClock"))
        self.Select.setText(_translate("MainWindow", "Select"))
        self.Load_dxf.setText(_translate("MainWindow", "Load Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
