# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Screen = QtWidgets.QWidget(self.centralwidget)
        self.Screen.setGeometry(QtCore.QRect(270, 0, 1091, 781))
        self.Screen.setObjectName("Screen")
        self.LoadMap = QtWidgets.QPushButton(self.centralwidget)
        self.LoadMap.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.LoadMap.setObjectName("LoadMap")
        self.AddGoal = QtWidgets.QPushButton(self.centralwidget)
        self.AddGoal.setGeometry(QtCore.QRect(140, 10, 93, 28))
        self.AddGoal.setObjectName("AddGoal")
        self.AddLine = QtWidgets.QPushButton(self.centralwidget)
        self.AddLine.setGeometry(QtCore.QRect(140, 50, 93, 28))
        self.AddLine.setObjectName("AddLine")
        self.EraseLine = QtWidgets.QPushButton(self.centralwidget)
        self.EraseLine.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.EraseLine.setObjectName("EraseLine")
        self.Select = QtWidgets.QPushButton(self.centralwidget)
        self.Select.setGeometry(QtCore.QRect(10, 90, 93, 28))
        self.Select.setObjectName("Select")
        self.Simulate = QtWidgets.QPushButton(self.centralwidget)
        self.Simulate.setGeometry(QtCore.QRect(10, 130, 93, 28))
        self.Simulate.setObjectName("Simulate")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(140, 130, 93, 28))
        self.Start.setObjectName("Start")
        self.Continue = QtWidgets.QPushButton(self.centralwidget)
        self.Continue.setGeometry(QtCore.QRect(140, 90, 93, 28))
        self.Continue.setObjectName("Continue")
        self.AddCoordinate = QtWidgets.QPushButton(self.centralwidget)
        self.AddCoordinate.setGeometry(QtCore.QRect(10, 170, 93, 28))
        self.AddCoordinate.setObjectName("AddCoordinate")
        self.AddObject = QtWidgets.QPushButton(self.centralwidget)
        self.AddObject.setGeometry(QtCore.QRect(140, 170, 93, 28))
        self.AddObject.setObjectName("AddObject")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadMap.setText(_translate("MainWindow", "LoadMap"))
        self.AddGoal.setText(_translate("MainWindow", "AddGoal"))
        self.AddLine.setText(_translate("MainWindow", "AddLine"))
        self.EraseLine.setText(_translate("MainWindow", "EraseLine"))
        self.Select.setText(_translate("MainWindow", "Select"))
        self.Simulate.setText(_translate("MainWindow", "Simulate"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.Continue.setText(_translate("MainWindow", "Continue"))
        self.AddCoordinate.setText(_translate("MainWindow", "AddCoordinate"))
        self.AddObject.setText(_translate("MainWindow", "AddObject"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
