# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diaglog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(338, 332)
        self.Chieu_rong = QtWidgets.QSpinBox(Dialog)
        self.Chieu_rong.setGeometry(QtCore.QRect(140, 30, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Chieu_rong.setFont(font)
        self.Chieu_rong.setObjectName("Chieu_rong")
        self.Ban_kinh = QtWidgets.QSpinBox(Dialog)
        self.Ban_kinh.setGeometry(QtCore.QRect(140, 80, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Ban_kinh.setFont(font)
        self.Ban_kinh.setObjectName("Ban_kinh")
        self.Vmax = QtWidgets.QDoubleSpinBox(Dialog)
        self.Vmax.setGeometry(QtCore.QRect(140, 140, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vmax.setFont(font)
        self.Vmax.setObjectName("Vmax")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(260, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(260, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Xác Nhận"))
        self.label.setText(_translate("Dialog", "Chiều rộng"))
        self.label_2.setText(_translate("Dialog", "Bán kính"))
        self.label_3.setText(_translate("Dialog", "Vmax"))
        self.label_4.setText(_translate("Dialog", "mm"))
        self.label_5.setText(_translate("Dialog", "mm"))
        self.label_6.setText(_translate("Dialog", "m/s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
